version: "3.3"

services:
  db:
    image: postgres:latest
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vapor
      POSTGRES_USER: vapor
      POSTGRES_PASSWORD: password